Lab6/Models/Employees.cs
namespace Lab6.Models
{
	public class Employees
	{
		public int Id { get; set; }
		public string FirstName { get; set; }
		public string LastName { get; set; }
		public string Email { get; set; }
		public string DateTime { get; set; }
		//public string Department {  get; set; }
		//public double Salary {  get; set; }
		//public string Phone { get; set; }
	}
}

Lab6/Models/ErrorViewModel.cs
namespace Lab6.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Lab6/Controllers/AddNewEmployeeController.cs
using Lab6.Interfaces;
using Lab6.Mocks;
using Lab6.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Lab6.Controllers
{
    public class AddNewEmployeeController : Controller
    {
        private readonly IEmployees _employeesService;

        public AddNewEmployeeController(IEmployees employeesService)
        {
            _employeesService = employeesService;
        }

        // Метод для відображення списку співробітників
        public IActionResult Index()
        {
            var employees = _employeesService.employees; // Отримуємо список співробітників
            return View(employees);
        }

        // Метод для відображення форми додавання співробітника (GET-запит)
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // Метод для обробки форми і додавання співробітника (POST-запит)
        [HttpPost]
        public IActionResult Create(Employees newEmployee)
        {
            var employeeList = (_employeesService as MockEmployees).employees;
            if (ModelState.IsValid)
            {
                newEmployee.Id = employeeList.Any() ? employeeList.Max(x => x.Id) + 1 : 1;
                // Додаємо нового співробітника через сервіс
                (_employeesService as MockEmployees)?.AddEmployee(newEmployee);

                // Повертаємо на сторінку з таблицею всіх співробітників
                return RedirectToAction("List", "AllEmployees");
            }
            return View(newEmployee);
        }
    }
}

Lab6/Controllers/AllEmployeesController.cs
using Lab6.Interfaces;
using Lab6.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lab6.Controllers
{
    public class AllEmployeesController : Controller
    {

        private readonly IEmployees _employeesService;

        public AllEmployeesController(IEmployees employeesService)
        {
            _employeesService = employeesService;
        }


        public IActionResult List()
        {
            var employees = _employeesService.employees;

            return View(employees);
        }

    }
}

Lab6/Views/AddNewEmployee/Create.cshtml
@model Lab6.Models.Employees

<h2>Add New Employee</h2>

<form asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="LastName"></label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
     <div class="form-group">
        <label asp-for="DateTime"></label>
        <input asp-for="DateTime" class="form-control" />
        <span asp-validation-for="DateTime" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Add Employee</button>
</form>

Lab6/Views/AllEmployees/List.cshtml
@model IEnumerable<Lab6.Models.Employees>

<h2>Employees List</h2>

<a asp-controller="AddNewEmployee" asp-action="Create" class="btn btn-success">Add New Employee</a>

<table class="table">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Data</th>
            <th>   </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var employee in Model)
        {
                    <tr>
                        <td>@employee.FirstName</td>
                        <td>@employee.LastName</td>
                        <td>@employee.Email</td>
                         <th>@employee.DateTime</th>
                          <td style="text-align:right;"> 

                        <button>
                                Delete
                            </button>

                            <button>
                                    Change
                                </button>
                    </tr>

        }
    </tbody>
</table>

Lab6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab6.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab6</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Lab6 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>